"""DeepResearch domain contracts and the offline v2 runtime boundary."""

from .contracts import (
    BriefApproval,
    BriefApprovalStatus,
    Citation,
    CitationRelation,
    Claim,
    ContractBundle,
    EvidenceLocator,
    EvidenceModality,
    EvidenceUnit,
    ResearchBrief,
    ResearchSubtask,
    ResearchTask,
    Source,
    SourceKind,
)
from .state import RunState, RunStatus, TransitionError
from .budgets import BudgetLedger, BudgetSpec, TokenUsage
from .errors import ErrorCode, ErrorSpec, ExecutionFailure, ManualInterventionRequired
from .operations import OperationJournal, OperationKind, OperationRecord, OperationStatus
from .policies import CancellationToken, ReplanDecision, ReplanPolicy, RetryPolicy
from .runtime_v2 import (
    CoordinatedCheckpointV2,
    CrashPoint,
    CrashSafeFakeHarness,
    DispatchInterrupted,
    RuntimeEventEnvelope,
    RuntimeEventType,
    UnifiedEventStore,
    replay_runtime_events,
)
from .canary import GLMCanaryPlan, GLMCanaryRunner
from .planner import FakePlanner, Planner, PlannerDraft, PlannerError, PlannerSubtaskDraft, ValidatedResearchPlan, plan_approved_brief, require_approved_brief
from .executor import EvidenceCandidate, EvidenceGraph, ExecutorError, LocalExecutorResult, LocalResearchExecutor, ReadOnlyToolRegistry, ToolName
from .gap_replan import EvidenceGap, GapConflictAssessment, PotentialConflict, ReplanDecisionRecord, ReplanOutcome, ReplannedResearchPlan, assess_evidence_graph, apply_bounded_replan, decide_replan
from .writer import FakeWriter, ReportDraft, ReportStatus, ReportValidationResult, SingleWriterRunner, ValidatedReport, Writer, validate_report_draft

__all__ = [
    "BriefApproval",
    "BriefApprovalStatus",
    "Citation",
    "CitationRelation",
    "Claim",
    "ContractBundle",
    "EvidenceLocator",
    "EvidenceModality",
    "EvidenceUnit",
    "ResearchBrief",
    "ResearchSubtask",
    "ResearchTask",
    "Source",
    "SourceKind",
    "RunState",
    "RunStatus",
    "TransitionError",
    "BudgetLedger",
    "BudgetSpec",
    "TokenUsage",
    "ErrorCode",
    "ErrorSpec",
    "ExecutionFailure",
    "ManualInterventionRequired",
    "OperationJournal",
    "OperationKind",
    "OperationRecord",
    "OperationStatus",
    "CancellationToken",
    "ReplanDecision",
    "ReplanPolicy",
    "RetryPolicy",
    "CoordinatedCheckpointV2",
    "CrashPoint",
    "CrashSafeFakeHarness",
    "DispatchInterrupted",
    "RuntimeEventEnvelope",
    "RuntimeEventType",
    "UnifiedEventStore",
    "replay_runtime_events",
    "GLMCanaryPlan",
    "GLMCanaryRunner",
    "FakePlanner",
    "Planner",
    "PlannerDraft",
    "PlannerError",
    "PlannerSubtaskDraft",
    "ValidatedResearchPlan",
    "plan_approved_brief",
    "require_approved_brief",
    "EvidenceCandidate",
    "EvidenceGraph",
    "ExecutorError",
    "LocalExecutorResult",
    "LocalResearchExecutor",
    "ReadOnlyToolRegistry",
    "ToolName",
    "EvidenceGap",
    "GapConflictAssessment",
    "PotentialConflict",
    "ReplanDecisionRecord",
    "ReplanOutcome",
    "ReplannedResearchPlan",
    "assess_evidence_graph",
    "apply_bounded_replan",
    "decide_replan",
    "FakeWriter",
    "ReportDraft",
    "ReportStatus",
    "ReportValidationResult",
    "SingleWriterRunner",
    "ValidatedReport",
    "Writer",
    "validate_report_draft",
]
